---
- name: Create user melvyn
  ansible.builtin.user:
    name: melvyn
    group: melvyn
    groups: ['wheel']
    shell: '/bin/bash'
    update_password: on_create
    password: '{{ user_password }}'
    append: true

- name: Create .ssh directory for melvyn
  ansible.builtin.file:
    path: /home/melvyn/.ssh
    state: directory
    owner: melvyn
    group: melvyn
    mode: '0700'

- name: Create authorized_keys for melvyn
  ansible.builtin.copy:
    dest: /home/melvyn/.ssh/authorized_keys
    owner: melvyn
    group: melvyn
    mode: '0600'
    content: '{{ authorized_keys }}'

- name: Create SSH config
  ansible.builtin.copy:
    dest: /home/melvyn/.ssh/config
    owner: melvyn
    group: melvyn
    mode: '0600'
    content: '{{ ssh_config }}'
