version: 0.2

phases:
  install:
    commands:
      - apk add --update --no-cache aws-cli ansible
      - aws configure set default.region eu-west-1
  pre_build:
    commands:
      - cd ami_builder
      - packer init .
      - packer validate .
  build:
    commands:
      - packer build -color=false aws-lmgateway.pkr.hcl
  post_build:
    commands:
      - echo 'Updating x86_64 Image ID in SSM Parameter Store'
      - >
        aws ssm put-parameter
        --output text
        --name '/mdekort/lmgateway/ami/x86_64'
        --overwrite
        --value
        "$(aws ec2 describe-images
        --filters 'Name=name,Values=mdekort-lmgateway-x86_64'
        --query 'Images[*].ImageId'
        --output text)"
      - echo 'Updating arm64 Image ID in SSM Parameter Store'
      - >
        aws ssm put-parameter
        --output text
        --name '/mdekort/lmgateway/ami/arm64'
        --overwrite
        --value
        $(aws ec2 describe-images
        --filters 'Name=name,Values=mdekort-lmgateway-arm64'
        --query 'Images[*].ImageId'
        --output text)
      - echo 'Refresh instances in ASG'
      - aws autoscaling start-instance-refresh --auto-scaling-group-name lmgateway
