version: 0.2

phases:
  install:
    runtime-versions:
      packer: 1
  pre_build:
    commands:
      - echo "Executing pre-build phase"
  build:
    commands:
      - echo "Executing build phase"
  post_build:
    commands:
      - echo "Executing post-build phase"

artifacts:
  files: "**/*"
  discard-paths: true
