---
- name: Run dante
  community.docker.docker_container:
    api_version: "1.44"
    name: dante
    image: wernight/dante:latest
    detach: true
    state: started
    network_mode: host
    restart_policy: always
