---
- name: 'LMGateway playbook'
  hosts: localhost
  connection: local
  become: true

  vars_files:
    - secrets.yml

  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - misc
    - users
    - ssm
    - fluent-bit
    - wireguard
