---
- name: 'LMGateway'
  hosts: localhost
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - misc
    - users
    - ssm
    - fluent_bit
    - role: dante
      vars:
        dante_version: 1.4.3
    - wireguard
