---
- name: 'Provision AMI'
  hosts: default
  become: true

  vars:
    ansible_python_interpreter: /usr/bin/python3

  roles:
    - misc
    - users
    - ssm
    - fluent_bit
    - docker
    - wireguard
    # - dante
