---
- name: Configure fluent-bit
  notify:
    - 'Enable fluent-bit'
  block:
    - name: Configure dnf repository
      ansible.builtin.copy:
        src: fluent-bit.repo
        dest: /etc/yum.repos.d/fluent-bit.repo
        owner: root
        group: root
        mode: '0644'

    - name: Install through dnf
      ansible.builtin.dnf:
        name: 'fluent-bit'
        state: present

    - name: Create lib directory
      ansible.builtin.file:
        path: /etc/fluent-bit/lib
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Create run directory
      ansible.builtin.file:
        path: /run/fluent-bit
        state: directory
        owner: root
        group: root
        mode: '0755'

    - name: Install New Relic plugin
      block:
        - name: Download plugin from GitHub (x86_64)
          when: ansible_architecture == 'x86_64'
          ansible.builtin.get_url:
            url: https://github.com/newrelic/newrelic-fluent-bit-output/releases/download/v1.17.3/out_newrelic-linux-amd64-1.17.3.so
            dest: /etc/fluent-bit/lib/out_newrelic.so
            owner: root
            group: root
            mode: '0644'
        - name: Download plugin from GitHub (arm64)
          when: ansible_architecture == 'aarch64'
          ansible.builtin.get_url:
            url: https://github.com/newrelic/newrelic-fluent-bit-output/releases/download/v1.17.3/out_newrelic-linux-arm64-1.17.3.so
            dest: /etc/fluent-bit/lib/out_newrelic.so
            owner: root
            group: root
            mode: '0644'

    - name: Plugin configuration
      ansible.builtin.copy:
        src: plugins.conf
        dest: /etc/fluent-bit/plugins.conf
        owner: root
        group: root
        mode: '0644'

    - name: Configuration file
      ansible.builtin.copy:
        src: fluent-bit.conf
        dest: /etc/fluent-bit/fluent-bit.conf
        owner: root
        group: root
        mode: '0644'
