---
- name: Configure Wireguard
  notify:
    - 'Reload network'
  block:
    - name: Configure netdev file
      ansible.builtin.copy:
        dest: /etc/systemd/network/wg0.netdev
        owner: root
        group: systemd-network
        mode: '0640'
        content: '{{ wireguard_netdev }}'

    - name: Configure network file
      ansible.builtin.copy:
        dest: /etc/systemd/network/wg0.network
        owner: root
        group: systemd-network
        mode: '0640'
        content: '{{ wireguard_network }}'
