---
- name: Configure docker
  block:
    - name: Install docker
      ansible.builtin.dnf:
        name: 'docker'
        state: present

    - name: Allow melvyn to run docker
      ansible.builtin.user:
        name: melvyn
        groups: docker
        append: true

    - name: Enable docker
      ansible.builtin.service:
        name: docker
        state: started
        enabled: true
