---
- name:
  ansible.builtin.copy:
    dest: /etc/systemd/network/wg0.netdev
    mode: '0640'
    owner: root:systemd-network
    content: '{{ wireguard_netdev }}'

- name:
  ansible.builtin.copy:
    dest: /etc/systemd/network/wg0.network
    mode: '0640'
    owner: root:systemd-network
    content: '{{ wireguard_network }}'

- name:
  ansible.builtin.copy:
    dest: /etc/dnsmasq.d/wireguard.conf
    mode: '0664'
    content: '{{ dnsmasq_conf }}'
