---
- name: Set root password
  ansible.builtin.user:
    name: root
    password: '{{ linux_password }}'

- name: Create user melvyn
  ansible.builtin.user:
    name: melvyn
    append: true
    groups: ['wheel']
    password: '{{ linux_password }}'
    shell: '/bin/bash'

- name: Create .ssh directory for melvyn
  ansible.builtin.file:
    path: /home/melvyn/.ssh
    state: directory
    mode: '0700'
    owner: melvyn:melvyn

- name: Create authorized_keys for melvyn
  ansible.builtin.copy:
    dest: /home/melvyn/.ssh/authorized_keys
    mode: '0664'
    owner: melvyn:melvyn
    content: '{{ authorized_keys }}'

- name:
  ansible.builtin.copy:
    dest: /home/melvyn/.ssh/config
    mode: '0600'
    owner: melvyn:melvyn
    content: '{{ ssh_config }}'
