name: "Ansible deploy"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ansible.yml'
      - 'ansible/**'

jobs:
  deploy:
    permissions:
      id-token: write
      contents: read
      pull-requests: write
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Configure AWS Credentials
        uses: aws-actions/configure-aws-credentials@v4
        with:
          aws-region: eu-west-1
          role-to-assume: arn:aws:iam::075673041815:role/external/deployer
      - name: Sync to S3 bucket
        run: aws s3 sync --delete ansible/ s3://mdekort.ansible/lmgateway/
