name: "Ansible Lint"

on:
  workflow_dispatch:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/ansible-lint.yml'
      - 'ami_builder/**'
  pull_request:
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    defaults:
      run:
        working-directory: ami_builder
    steps:
      - name: Checkout
        uses: actions/checkout@v5
      - name: Install Python
        uses: actions/setup-python@v6
        with:
          python-version: '3.10'
      - name: Install Ansible
        run: python3 -m pip install --user ansible ansible-lint
      - name: Install Requirements
        run: ansible-galaxy install -r requirements.yml
      - name: Run ansible-lint
        run: ansible-lint
